"""add storage_path to images

Revision ID: 7afe72ddfa5f
Revises: 
Create Date: 2025-01-18 00:24:44.765431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7afe72ddfa5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_processings', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('image_processings', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('image_processings', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('image_processings', 'api_start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('image_processings', 'api_end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_image_processings_created_at', table_name='image_processings')
    op.drop_index('ix_image_processings_image_id', table_name='image_processings')
    op.drop_index('ix_image_processings_job_id', table_name='image_processings')
    op.drop_index('ix_image_processings_model_version', table_name='image_processings')
    op.drop_index('ix_image_processings_start_time', table_name='image_processings')
    op.drop_index('ix_image_processings_status', table_name='image_processings')
    op.drop_index('ix_image_processings_user_id', table_name='image_processings')
    op.create_unique_constraint(None, 'image_processings', ['job_id'])
    op.drop_constraint('image_processings_image_id_fkey', 'image_processings', type_='foreignkey')
    op.create_foreign_key(None, 'image_processings', 'images', ['image_id'], ['id'])
    op.drop_column('image_processings', 'created_at')
    op.add_column('images', sa.Column('storage_path', sa.String(), nullable=True))
    op.alter_column('images', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_images_gcs_key', table_name='images')
    op.drop_index('ix_images_uploaded_at', table_name='images')
    op.drop_index('ix_images_user_id', table_name='images')
    op.drop_column('images', 'gcs_key')
    op.drop_column('images', 'gcs_bucket')
    op.drop_column('images', 'mime_type')
    op.drop_column('images', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('gcs_bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('gcs_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_images_user_id', 'images', ['user_id'], unique=False)
    op.create_index('ix_images_uploaded_at', 'images', ['uploaded_at'], unique=False)
    op.create_index('ix_images_gcs_key', 'images', ['gcs_key'], unique=False)
    op.alter_column('images', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('images', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('images', 'storage_path')
    op.add_column('image_processings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_processings', type_='foreignkey')
    op.create_foreign_key('image_processings_image_id_fkey', 'image_processings', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'image_processings', type_='unique')
    op.create_index('ix_image_processings_user_id', 'image_processings', ['user_id'], unique=False)
    op.create_index('ix_image_processings_status', 'image_processings', ['status'], unique=False)
    op.create_index('ix_image_processings_start_time', 'image_processings', ['start_time'], unique=False)
    op.create_index('ix_image_processings_model_version', 'image_processings', ['model_version'], unique=False)
    op.create_index('ix_image_processings_job_id', 'image_processings', ['job_id'], unique=True)
    op.create_index('ix_image_processings_image_id', 'image_processings', ['image_id'], unique=False)
    op.create_index('ix_image_processings_created_at', 'image_processings', ['created_at'], unique=False)
    op.alter_column('image_processings', 'api_end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('image_processings', 'api_start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('image_processings', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('image_processings', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('image_processings', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
